services:
  report-transformer:
    build: .
    volumes:
      - ./import:/data/import
      - ./output:/data/output
      - ./config:/app/config
    environment:
      - APP_IMPORT_DIR=/data/import
      - APP_OUTPUT_DIR=/data/output
      - APP_TEMPLATE_PATH=/data/import/template.xlsx
      - APP_LAST_YEAR_DIR=/data/import/lastyear
